from pydantic import BaseModel
from agents.items import TResponseInputItem
import json

class ReflectionOutput(BaseModel):
    status: str
    reason: str

class ReflectionSuccessOutput(ReflectionOutput):
    extracted_content: str
    source: str

def get_reflection_success_instruction() -> str:
    return """
You are a Navigation Decision Evaluator.

You are reviewing a navigation session in which the agent has generated a response indicating task completion. Your goal is to determine whether the navigation actions and output fully satisfy the user's query.

## Decision Framework
A. adequate
  - The final output and navigation trajectory provide a complete and comprehensive answer to the User Query. The answer needs to cover all questions of the User Query.
  - No further navigation is needed.

B. inadequate
  - The output is partial or relevant, but does not fully answer the User Query.
  - Further navigation on following links is likely to provide the missing information.

## Output Format
Output a JSON object.
{
    "status": "adequate" | "inadequate",
    "reason": "Explain why the current output is sufficient or why we should continue.",
    "output": "The response generated by the navigation agent.",
    "source": "The URL where the content was extracted from."
}
"""

class ReflectionFailureOutput(ReflectionOutput):
    pass

def get_reflection_failure_instruction() -> str:
    return """
You are a Navigation Decision Evaluator.

The web navigation agent has exhausted its navigation budget before completing the task. Your goal is to analyze the navigation trajectory and the final URL to decide if this path is promising and should be continued, or if it should be abandoned.

## Decision Framework
A. feasible
  - The answer was not found yet, but the current page is relevant to the User Query.
  - The stop might be due to budget constraints, but the agent simply needs to visit more links or navigate deeper on this site.
  - We should NOT give up on this path yet.

B. infeasible
  - The page is irrelevant, a dead end, or the site is broken.
  - Repeated actions in the trajectory suggest no answer exists here.
  - We should abandon this path.

## Output Format
Output a JSON object.

{
    "status": "feasible" | "infeasible",
    "reason": "Explain why the current trajectory is promising vs. why it leads to a dead end."
}
"""

def get_function_list(input_list: list[TResponseInputItem]) -> list[TResponseInputItem]:
    used_tool_list = []
    for item in input_list:
        if "type" not in item:
            continue
        if item["type"] == "function_call":
            used_tool_list.append((item["name"], item["arguments"]))

    return used_tool_list